// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: pronosticos.flex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\2\22\0\1\4"+
    "\1\0\1\5\5\0\1\6\1\7\1\10\1\0\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\6\21"+
    "\1\22\5\0\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\2\25\1\32\1\33\2\25\1\34\1\35\1\36"+
    "\1\37\1\25\1\40\1\41\4\25\1\42\2\25\1\43"+
    "\1\0\1\44\1\0\1\45\1\0\1\46\1\47\1\50"+
    "\1\51\1\52\1\25\1\53\1\25\1\54\2\25\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\25\1\70\1\71\1\72\12\0\1\3"+
    "\73\0\1\73\7\0\1\73\3\0\1\73\3\0\1\73"+
    "\1\0\1\73\6\0\1\73\1\0\1\73\4\0\1\73"+
    "\7\0\1\73\3\0\1\73\3\0\1\73\1\0\1\73"+
    "\6\0\1\73\1\0\1\73\u012b\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\3\1\4\1\1\5\5"+
    "\1\6\14\7\1\10\1\11\5\0\3\5\20\7\1\12"+
    "\1\13\2\0\1\5\5\0\20\7\2\0\1\5\31\0"+
    "\16\7\4\0\1\5\31\0\10\7\1\14\1\0\1\15"+
    "\33\0\7\7\1\0\1\15\24\0\2\7\1\16\3\7"+
    "\1\0\1\15\12\0\1\7\1\17\1\7\1\0\1\7"+
    "\11\0\2\7\1\0\1\7\1\0\2\20\1\21\1\7"+
    "\1\0\1\7\1\0\1\7\1\0\1\7\1\0\1\7"+
    "\1\22\2\0\1\23\15\0\1\24\1\0\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\74\0\u0168"+
    "\0\u0168\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\74\0\u02d0"+
    "\0\u030c\0\u0348\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0"+
    "\0\u04ec\0\u0528\0\u0564\0\74\0\74\0\u05a0\0\u05dc\0\u0618"+
    "\0\u0168\0\u0654\0\u0690\0\u06cc\0\u0708\0\u0744\0\u0780\0\u07bc"+
    "\0\u07f8\0\u0834\0\u0870\0\u08ac\0\u08e8\0\u0924\0\u0960\0\u099c"+
    "\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\74\0\74\0\u0b04"+
    "\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4"+
    "\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4"+
    "\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4"+
    "\0\u10e0\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284"+
    "\0\u12c0\0\u12fc\0\u1338\0\u1374\0\u13b0\0\u13ec\0\u1428\0\u1464"+
    "\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590\0\u15cc\0\u1608\0\u1644"+
    "\0\u1680\0\u16bc\0\u16f8\0\u1734\0\u1770\0\u17ac\0\u17e8\0\u1824"+
    "\0\u1860\0\u189c\0\u18d8\0\u1914\0\u1950\0\u198c\0\u19c8\0\u1a04"+
    "\0\u1a40\0\u1a7c\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c\0\u1ba8\0\u1be4"+
    "\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10\0\u1d4c\0\u1d88\0\u1dc4"+
    "\0\u1e00\0\u1e3c\0\u1e78\0\u1eb4\0\u1ef0\0\u1f2c\0\u1f68\0\u1fa4"+
    "\0\u1fe0\0\u201c\0\u2058\0\u2094\0\u20d0\0\u210c\0\u2148\0\u2184"+
    "\0\u21c0\0\u21fc\0\u2238\0\u2274\0\u22b0\0\u22ec\0\u2328\0\u030c"+
    "\0\u2364\0\u23a0\0\u23dc\0\u2418\0\u2454\0\u2490\0\u24cc\0\u2508"+
    "\0\u2544\0\u2580\0\u25bc\0\u25f8\0\u2634\0\u2670\0\u26ac\0\u26e8"+
    "\0\u2724\0\u2760\0\u279c\0\u27d8\0\u2814\0\u2850\0\u288c\0\u28c8"+
    "\0\u2904\0\u2940\0\u297c\0\u29b8\0\u29f4\0\u2a30\0\u2a6c\0\u2aa8"+
    "\0\u2ae4\0\u2b20\0\u2b5c\0\u2b98\0\u2bd4\0\u2c10\0\u2c4c\0\u2c88"+
    "\0\u2cc4\0\u2d00\0\u2d3c\0\u2d78\0\u2db4\0\u2df0\0\u2e2c\0\u2e68"+
    "\0\u2ea4\0\u2ee0\0\u2f1c\0\u2f58\0\u2f94\0\u2fd0\0\u300c\0\u3048"+
    "\0\u3084\0\u30c0\0\u30fc\0\u3138\0\u030c\0\u3174\0\u31b0\0\u31ec"+
    "\0\u3228\0\u3264\0\u32a0\0\u32dc\0\u3318\0\u3354\0\u3390\0\u33cc"+
    "\0\u3408\0\u3444\0\u3480\0\u34bc\0\u34f8\0\74\0\u3534\0\u3570"+
    "\0\u35ac\0\u35e8\0\u3624\0\u3660\0\u369c\0\u36d8\0\u3714\0\u3750"+
    "\0\u378c\0\u37c8\0\u3804\0\u3840\0\u387c\0\u38b8\0\u38f4\0\u0168"+
    "\0\74\0\u030c\0\u3930\0\u396c\0\u39a8\0\u39e4\0\u3a20\0\u3a5c"+
    "\0\u3a98\0\u3ad4\0\u3b10\0\74\0\u3b4c\0\u3b88\0\74\0\u3bc4"+
    "\0\u3c00\0\u3c3c\0\u3c78\0\u3cb4\0\u3cf0\0\u3d2c\0\u3d68\0\u3da4"+
    "\0\u3de0\0\u3e1c\0\u3e58\0\u3e94\0\74\0\u3ed0\0\74";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\2\1\6"+
    "\1\7\1\10\1\11\1\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\2\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\21\1\26\1\27\1\30\1\31\1\32\1\21"+
    "\1\33\1\21\1\34\1\35\1\11\26\21\75\0\2\3"+
    "\1\0\1\3\67\0\2\36\1\0\2\36\1\0\66\36"+
    "\42\0\1\37\43\0\1\40\73\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\41\2\0\27\41\12\0\2\41\1\0"+
    "\1\43\4\44\1\0\1\42\17\41\2\0\27\41\12\0"+
    "\2\41\1\0\3\44\2\45\1\0\1\42\17\41\2\0"+
    "\27\41\12\0\2\41\1\0\5\45\1\0\1\42\17\41"+
    "\2\0\27\41\12\0\2\41\1\0\2\45\3\43\1\0"+
    "\1\42\17\41\2\0\27\41\12\0\2\41\1\0\5\43"+
    "\1\0\1\42\17\41\2\0\27\41\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\1\21\1\46"+
    "\3\21\1\47\20\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\26\21\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\1\50\25\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\6\21\1\51\17\21\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\21\2\0\1\41\11\21\1\52\2\21"+
    "\1\53\11\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\4\21\1\54\1\21\1\55\17\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\20\21\1\56\5\21\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\21\2\0\1\41\1\57\25\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\12\21\1\60\13\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\2\21\1\61\23\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\1\62\14\21\1\63\10\21\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\4\21\1\64\12\21\2\0\1\41\4\21"+
    "\1\65\21\21\2\36\1\0\2\36\1\66\66\36\7\0"+
    "\1\67\74\0\1\70\100\0\5\71\2\0\17\71\3\0"+
    "\26\71\12\0\2\41\1\0\5\72\1\0\1\42\17\41"+
    "\2\0\27\41\4\0\1\73\5\0\1\74\1\75\1\76"+
    "\5\72\1\0\1\42\17\41\2\0\27\41\4\0\1\73"+
    "\5\0\1\74\1\75\1\77\5\72\1\0\1\42\17\41"+
    "\2\0\27\41\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\15\21\1\100\10\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\12\21"+
    "\1\101\13\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\10\21\1\102\15\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\2\21"+
    "\1\103\23\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\4\21\1\104\21\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\20\21"+
    "\1\105\5\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\1\21\1\106\24\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\22\21"+
    "\1\107\3\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\7\21\1\110\1\21\1\110\14\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\15\21\1\111\5\21\1\112\2\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\21\21"+
    "\1\103\4\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\17\21\1\113\6\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\15\21"+
    "\1\114\10\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\12\21\1\115\13\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\14\21\1\116\2\21\2\0"+
    "\1\41\26\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\13\21\1\117\12\21\12\0\1\120"+
    "\74\0\1\121\1\0\5\71\2\0\17\71\3\0\26\71"+
    "\12\0\2\41\1\0\5\122\1\0\1\42\17\41\2\0"+
    "\27\41\24\0\1\123\2\0\1\124\1\125\1\126\1\0"+
    "\1\127\1\130\1\131\1\132\2\0\1\133\44\0\2\41"+
    "\1\0\5\41\1\0\1\42\1\134\2\41\1\135\1\136"+
    "\1\137\1\41\1\140\1\141\1\142\1\143\2\41\1\144"+
    "\1\41\2\0\27\41\12\0\2\41\1\0\1\145\1\146"+
    "\3\41\1\0\1\42\17\41\2\0\27\41\15\0\1\147"+
    "\2\150\1\151\70\0\1\147\1\152\61\0\1\153\5\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\6\21\1\154\17\21\4\0\1\153\5\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\16\21\1\155"+
    "\7\21\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\13\21\1\156\12\21\4\0\1\153\5\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\6\21\1\157\17\21\4\0\1\153\5\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\15\21\1\160"+
    "\10\21\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\6\21\1\161\17\21\4\0\1\153\5\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\15\21\1\162\10\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\17\21\1\163\6\21\4\0"+
    "\1\153\5\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\6\21\1\160\17\21\4\0\1\153\5\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\24\21\1\160\1\21\4\0\1\153\5\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\12\21\1\164"+
    "\13\21\4\0\1\153\5\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\20\21\1\165\5\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\17\21\1\166\6\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\11\21\1\167\14\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\6\21\1\170\10\21"+
    "\2\0\1\41\26\21\4\0\1\153\5\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\17\21\1\171"+
    "\6\21\10\0\1\172\107\0\17\173\3\0\25\173\13\0"+
    "\1\174\1\41\1\175\5\176\1\0\1\42\17\41\2\0"+
    "\27\41\47\0\1\177\3\0\1\200\74\0\1\201\76\0"+
    "\1\202\66\0\1\203\107\0\1\204\53\0\1\205\105\0"+
    "\1\206\63\0\1\207\75\0\1\210\33\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\2\41\1\211\3\41"+
    "\1\212\20\41\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\41\2\0\7\41\1\213\17\41\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\12\41\1\214\14\41"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\41\2\0"+
    "\5\41\1\215\21\41\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\41\2\0\21\41\1\216\5\41\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\1\41\1\217"+
    "\25\41\12\0\2\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\13\41\1\220\13\41\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\41\2\0\3\41\1\221\23\41\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\41\2\0\5\41"+
    "\1\222\21\41\12\0\2\41\1\0\1\41\4\223\1\0"+
    "\1\42\17\41\2\0\27\41\12\0\2\41\1\0\3\223"+
    "\2\41\1\0\1\42\17\41\2\0\27\41\16\0\4\224"+
    "\67\0\5\224\67\0\2\224\72\0\3\224\71\0\1\225"+
    "\2\226\1\227\65\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\7\21\1\164\16\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\17\21"+
    "\1\160\6\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\4\21\1\230\21\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\4\21"+
    "\1\231\21\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\12\21\1\164\13\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\13\21"+
    "\1\232\12\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\4\21\1\233\21\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\20\21"+
    "\1\234\5\21\4\0\1\153\5\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\21\2\0\1\41\26\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\1\21"+
    "\1\235\24\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\6\21\1\236\17\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\12\21"+
    "\1\237\13\21\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\4\21\1\240\12\21\2\0\1\41\26\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\6\21"+
    "\1\157\17\21\12\0\1\241\105\0\17\242\3\0\25\242"+
    "\13\0\2\41\1\0\1\243\1\244\3\41\1\0\1\42"+
    "\17\41\2\0\27\41\15\0\1\245\1\246\67\0\2\41"+
    "\1\0\5\176\1\0\1\42\17\41\2\0\27\41\63\0"+
    "\1\247\70\0\1\250\63\0\1\251\75\0\1\252\70\0"+
    "\1\253\101\0\1\254\1\0\1\254\77\0\1\255\5\0"+
    "\1\256\71\0\1\251\71\0\1\257\67\0\1\260\24\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\41\2\0\16\41"+
    "\1\261\10\41\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\41\2\0\13\41\1\262\13\41\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\3\41\1\263\23\41"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\41\2\0"+
    "\5\41\1\264\21\41\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\41\2\0\2\41\1\265\24\41\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\10\41\1\266"+
    "\1\41\1\266\14\41\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\41\2\0\16\41\1\267\5\41\1\270\2\41"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\41\2\0"+
    "\22\41\1\263\4\41\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\41\2\0\20\41\1\271\6\41\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\14\41\1\272"+
    "\12\41\12\0\1\41\1\273\1\0\5\41\1\0\1\42"+
    "\17\41\2\0\27\41\14\0\1\274\75\0\4\275\67\0"+
    "\5\275\67\0\2\275\67\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\12\21\1\276\13\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\10\21\1\165\15\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\12\21\1\277\13\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\15\21\1\160\10\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\15\21\1\300\10\21\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\15\21\1\301\10\21\12\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\2\21\1\302\1\303\22\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\16\21\1\304\7\21\10\0\1\305\76\0\1\121"+
    "\10\0\17\306\3\0\25\306\13\0\2\41\1\0\1\41"+
    "\4\307\1\0\1\42\17\41\2\0\27\41\12\0\2\41"+
    "\1\0\3\307\2\41\1\0\1\42\17\41\2\0\27\41"+
    "\16\0\4\310\67\0\3\310\60\0\1\274\47\0\1\311"+
    "\23\0\1\274\57\0\1\312\13\0\1\274\47\0\1\313"+
    "\23\0\1\274\56\0\1\314\14\0\1\274\56\0\1\315"+
    "\14\0\1\274\47\0\1\314\23\0\1\274\65\0\1\314"+
    "\5\0\1\274\53\0\1\316\17\0\1\274\61\0\1\317"+
    "\11\0\1\274\60\0\1\320\20\0\1\273\1\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\7\41\1\321\17\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\17\41\1\322\7\41\12\0\1\273\1\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\7\41\1\323\17\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\16\41\1\324\10\41\12\0\1\273\1\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\16\41\1\325\10\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\7\41\1\324\17\41\12\0\1\273\1\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\25\41\1\324\1\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\13\41\1\326\13\41\12\0\1\273\1\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\21\41\1\327\5\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\20\41\1\330\6\41\12\0\2\41\1\0\5\331"+
    "\1\0\1\42\17\41\2\0\27\41\15\0\5\332\63\0"+
    "\1\274\74\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\11\21\1\333\14\21\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\16\21\1\334"+
    "\7\21\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\4\21\1\335\21\21\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\4\21\1\164"+
    "\21\21\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\6\21\1\336\17\21\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\12\21\1\337"+
    "\13\21\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\17\21\1\340\6\21\12\0\1\341\74\0"+
    "\1\121\10\0\17\342\3\0\25\342\13\0\1\343\1\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\27\41\14\0"+
    "\1\344\134\0\1\316\103\0\1\314\60\0\1\345\101\0"+
    "\1\316\65\0\1\346\25\0\1\274\136\0\1\347\100\0"+
    "\1\313\31\0\2\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\10\41\1\326\16\41\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\41\2\0\20\41\1\324\6\41\12\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\41\2\0\5\41"+
    "\1\350\21\41\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\41\2\0\13\41\1\326\13\41\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\5\41\1\351\21\41"+
    "\12\0\1\273\1\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\27\41\12\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\41\2\0\2\41\1\352\24\41\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\41\2\0\7\41\1\323\17\41"+
    "\12\0\2\41\1\0\5\353\1\0\1\42\17\41\2\0"+
    "\27\41\15\0\5\354\64\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\1\355\25\21\12\0\2\41"+
    "\1\0\5\41\1\356\1\42\17\21\2\0\1\41\26\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\13\21\1\357\12\21\4\0\1\360\5\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\26\21"+
    "\12\0\2\41\1\0\5\41\1\0\1\42\17\21\2\0"+
    "\1\41\6\21\1\361\17\21\10\0\1\362\76\0\1\121"+
    "\72\0\2\41\1\0\1\363\2\364\1\365\1\41\1\0"+
    "\1\42\17\41\2\0\27\41\15\0\1\366\2\367\1\370"+
    "\131\0\1\317\100\0\1\314\73\0\1\371\22\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\11\41\1\327"+
    "\15\41\12\0\2\41\1\0\5\41\1\0\1\42\17\41"+
    "\2\0\16\41\1\324\10\41\12\0\2\41\1\0\5\41"+
    "\1\0\1\42\17\41\2\0\16\41\1\372\10\41\12\0"+
    "\2\41\1\0\5\364\1\0\1\42\17\41\2\0\27\41"+
    "\15\0\5\367\64\0\2\41\1\0\5\41\1\0\1\42"+
    "\17\21\2\0\1\41\17\21\1\373\6\21\12\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\21\2\0\1\41\1\374"+
    "\25\21\35\0\1\375\50\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\2\21\1\376\23\21\12\0"+
    "\1\377\73\0\2\41\1\0\1\41\4\u0100\1\0\1\42"+
    "\17\41\2\0\27\41\12\0\2\41\1\0\5\u0100\1\0"+
    "\1\42\17\41\2\0\27\41\12\0\2\41\1\0\2\u0100"+
    "\3\41\1\0\1\42\17\41\2\0\27\41\16\0\4\u0101"+
    "\67\0\5\u0101\67\0\2\u0101\127\0\1\316\33\0\2\41"+
    "\1\0\5\41\1\0\1\42\17\41\2\0\5\41\1\326"+
    "\21\41\12\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\12\21\1\u0102\13\21\12\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\11\21\1\u0103"+
    "\14\21\63\0\1\u0104\22\0\2\41\1\0\5\41\1\0"+
    "\1\42\17\21\2\0\1\41\12\21\1\u0105\13\21\10\0"+
    "\1\u0106\75\0\2\41\1\0\5\41\1\0\1\42\17\21"+
    "\2\0\1\41\17\21\1\u0107\6\21\60\0\1\u0108\25\0"+
    "\2\41\1\0\5\41\1\0\1\42\17\21\2\0\1\41"+
    "\16\21\1\u0109\7\21\12\0\1\u010a\73\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\4\21\1\u010b"+
    "\21\21\22\0\1\u010c\55\0\1\u010d\5\0\2\41\1\0"+
    "\5\41\1\0\1\42\17\21\2\0\1\41\26\21\10\0"+
    "\1\u010e\75\0\2\41\1\0\5\41\1\u010f\1\42\17\21"+
    "\2\0\1\41\26\21\37\0\1\u0110\46\0\1\u0111\127\0"+
    "\1\u0112\35\0\1\u0113\146\0\1\u0114\22\0\1\u0115\146\0"+
    "\1\u0116\16\0\1\u0117\137\0\1\u0118\31\0\1\u0119\132\0"+
    "\1\u011a\32\0\1\u011b\143\0\1\u011c\25\0\1\u011d\145\0"+
    "\1\u011e\31\0\1\u011f\51\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[16140];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\7\1\1\11\14\1\2\11"+
    "\5\0\23\1\2\11\2\0\1\1\5\0\20\1\2\0"+
    "\1\1\31\0\16\1\4\0\1\1\31\0\11\1\1\0"+
    "\1\1\33\0\7\1\1\0\1\1\24\0\6\1\1\0"+
    "\1\1\12\0\1\1\1\11\1\1\1\0\1\1\11\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\11\2\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\2\0\1\11\15\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Metodo de creacion de TOKENS sin value (solo el tipo de Token)
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    // Metodo de creacion de TOKENS con value (tipo de token y contenido)
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Err, No se reconoce: " + yytext());
            }
          // fall through
          case 22: break;
          case 2:
            { 
            }
          // fall through
          case 23: break;
          case 3:
            { return symbol(sym.COMA);
            }
          // fall through
          case 24: break;
          case 4:
            { return symbol(sym.GUION);
            }
          // fall through
          case 25: break;
          case 5:
            { return symbol(sym.NUMERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 26: break;
          case 6:
            { return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 27: break;
          case 7:
            { return symbol(sym.NOMBRE, yytext().trim());
            }
          // fall through
          case 28: break;
          case 8:
            { return symbol(sym.CORCHETE_ABRE);
            }
          // fall through
          case 29: break;
          case 9:
            { return symbol(sym.CORCHETE_CIERRE);
            }
          // fall through
          case 30: break;
          case 10:
            { return symbol(sym.ESTADIO, yytext().substring(1, yytext().length()-1));
            }
          // fall through
          case 31: break;
          case 11:
            { return symbol(sym.DOBLE);
            }
          // fall through
          case 32: break;
          case 12:
            { return symbol(sym.SERIE);
            }
          // fall through
          case 33: break;
          case 13:
            { return symbol(sym.EMAIL, yytext());
            }
          // fall through
          case 34: break;
          case 14:
            { return symbol(sym.FIXTURE);
            }
          // fall through
          case 35: break;
          case 15:
            { return symbol(sym.EQUIPOS);
            }
          // fall through
          case 36: break;
          case 16:
            { return symbol(sym.FECHA, yytext());
            }
          // fall through
          case 37: break;
          case 17:
            { return symbol(sym.CAMPEONATO);
            }
          // fall through
          case 38: break;
          case 18:
            { return symbol(sym.PARTIDO_NRO);
            }
          // fall through
          case 39: break;
          case 19:
            { return symbol(sym.PARTICIPANTE);
            }
          // fall through
          case 40: break;
          case 20:
            { return symbol(sym.SEPARADOR);
            }
          // fall through
          case 41: break;
          case 21:
            { return symbol(sym.PRONOSTICOS_PARTIDOS);
            }
          // fall through
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
