
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\004\000\002\002\006\000\002\003" +
    "\005\000\002\017\003\000\002\017\004\000\002\004\003" +
    "\000\002\005\003\000\002\005\004\000\002\006\011\000" +
    "\002\010\003\000\002\010\004\000\002\007\003\000\002" +
    "\007\005\000\002\011\003\000\002\011\004\000\002\012" +
    "\014\000\002\013\003\000\002\013\004\000\002\014\011" +
    "\000\002\015\003\000\002\015\004\000\002\016\011\000" +
    "\002\016\012" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\004\005\001\002\000\004\005\014\001" +
    "\002\000\004\026\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\012\007\ufffe\017\ufffe\022" +
    "\ufffe\026\ufffe\001\002\000\006\022\012\026\013\001\002" +
    "\000\004\005\uffff\001\002\000\012\007\ufffd\017\ufffd\022" +
    "\ufffd\026\ufffd\001\002\000\004\006\ufffc\001\002\000\004" +
    "\006\020\001\002\000\006\006\020\020\050\001\002\000" +
    "\006\006\ufffb\020\ufffb\001\002\000\004\026\010\001\002" +
    "\000\006\007\022\026\013\001\002\000\004\013\023\001" +
    "\002\000\004\026\025\001\002\000\006\014\031\015\030" +
    "\001\002\000\012\014\ufff8\015\ufff8\022\ufff8\026\ufff8\001" +
    "\002\000\010\014\ufff6\015\ufff6\026\027\001\002\000\012" +
    "\014\ufff7\015\ufff7\022\ufff7\026\ufff7\001\002\000\004\026" +
    "\025\001\002\000\004\010\032\001\002\000\004\022\036" +
    "\001\002\000\010\006\ufff4\010\ufff4\020\ufff4\001\002\000" +
    "\010\006\ufff9\010\032\020\ufff9\001\002\000\010\006\ufff3" +
    "\010\ufff3\020\ufff3\001\002\000\004\023\037\001\002\000" +
    "\004\017\040\001\002\000\004\025\041\001\002\000\004" +
    "\026\025\001\002\000\006\022\043\026\027\001\002\000" +
    "\004\017\044\001\002\000\004\026\025\001\002\000\006" +
    "\022\046\026\027\001\002\000\010\006\ufff2\010\ufff2\020" +
    "\ufff2\001\002\000\010\014\ufff5\015\ufff5\026\027\001\002" +
    "\000\004\011\055\001\002\000\006\006\ufffa\020\ufffa\001" +
    "\002\000\006\002\ufff1\020\ufff1\001\002\000\006\002\000" +
    "\020\050\001\002\000\006\002\ufff0\020\ufff0\001\002\000" +
    "\004\026\010\001\002\000\006\017\057\026\013\001\002" +
    "\000\004\024\060\001\002\000\004\012\061\001\002\000" +
    "\004\022\062\001\002\000\004\016\066\001\002\000\010" +
    "\002\uffef\020\uffef\022\062\001\002\000\010\002\uffee\020" +
    "\uffee\022\uffee\001\002\000\010\002\uffed\020\uffed\022\uffed" +
    "\001\002\000\006\021\067\026\025\001\002\000\004\026" +
    "\025\001\002\000\006\022\071\026\027\001\002\000\004" +
    "\017\072\001\002\000\004\026\025\001\002\000\006\022" +
    "\074\026\027\001\002\000\010\002\uffec\020\uffec\022\uffec" +
    "\001\002\000\006\022\076\026\027\001\002\000\004\017" +
    "\077\001\002\000\004\026\025\001\002\000\006\022\101" +
    "\026\027\001\002\000\010\002\uffeb\020\uffeb\022\uffeb\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\006\002\005\003\003\001\001\000\004\004" +
    "\014\001\001\000\004\017\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\015\006\016\001\001\000\010\006\050\013\052\014" +
    "\051\001\001\000\002\001\001\000\004\017\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\007\023\010" +
    "\025\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\046\001\001\000" +
    "\006\011\033\012\032\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\012\034\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\053\001\001\000\002\001\001" +
    "\000\004\017\055\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\015\062\016\063\001\001" +
    "\000\002\001\001\000\004\016\064\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\067\001\001\000\004" +
    "\010\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\072\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\077\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    //Crear Campeonato
    //Aca van variables globales (se pueden acceder desde cualquier parte del codigo)
    Campeonato campeonatoActual = null;

    //Guarda la ultima serie leída (esto es para cosas como saber cual es la serie de los partidos que se estan leyendo)
    Serie serieActual = null;

    Map<Integer, Partido> partidosPorNumero = new HashMap<>();

    List<Participante> participantes = new ArrayList<>();


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= campeonato fixture series participantes_nt 
            {
              Object RESULT =null;
		
        // ===== VALIDAR CANTIDAD TOTAL DE SERIES =====
        int cant = campeonatoActual.getSeries().size();
        if (cant != 4 && cant != 8 && cant != 12) {
            System.err.println(
                "ERROR: Se encontraron " + cant + " series. Deben ser 4, 8 o 12."
            );
        }

        // =====================================================
        // === PROCESAMIENTO GLOBAL - IMPRESIÓN COMPLETA ======
        // =====================================================

        System.out.println("\n\n=======================================");
        System.out.println("     PROCESAMIENTO FINAL DEL ARCHIVO   ");
        System.out.println("=======================================\n");

        // ===== IMPRIMIR CAMPEONATO =====
        System.out.println("=== CAMPEONATO ===");
        System.out.println(campeonatoActual.getNombre() + " " + campeonatoActual.getAnio());

        // ===== IMPRIMIR TODAS LAS SERIES =====
        System.out.println("\n=== SERIES ===");
        for (Serie s : campeonatoActual.getSeries()) {

            System.out.println("\n---------------------------------------");
            System.out.println("Serie: " + s.getNombre());
            System.out.println("---------------------------------------");

            // Equipos
            System.out.println("Equipos:");
            for (String eq : s.getEquipos()) {
                System.out.println(" • " + eq);
            }

            // Partidos
            System.out.println("\nPartidos del Grupo:");
            for (Partido p : s.getPartidos()) {
                System.out.println("  Partido " + p.getNumero() +
                    " | " + p.getFecha() +
                    " | " + p.getEstadio() +
                    " | " + p.getEquipoLocal() + " " + p.getGolesLocal() +
                    " - " + p.getGolesVisitante() + " " + p.getEquipoVisitante());
            }
        }

        // ===== IMPRIMIR LISTA GLOBAL DE PARTIDOS (TU BLOQUE, CORREGIDO) =====
        System.out.println("\n=== LISTA GLOBAL DE PARTIDOS CARGADOS ===");
        for (Partido partido : partidosPorNumero.values()) {
            System.out.println("======================================================");
            System.out.println("Partido: " + partido.getNumero());
            System.out.println("Fecha: " + partido.getFecha());
            System.out.println("Estadio: " + partido.getEstadio());
            System.out.println("Equipo Local: " + partido.getEquipoLocal());
            System.out.println("Equipo Visitante: " + partido.getEquipoVisitante());
            System.out.println("Resultado: " + partido.getEquipoLocal() + " " + partido.getGolesLocal() +
                               " - " + partido.getGolesVisitante() + " " + partido.getEquipoVisitante());
            System.out.println("======================================================");
        }

        // ===== IMPRIMIR PARTICIPANTES Y SUS PRONÓSTICOS =====
        System.out.println("\n=== PARTICIPANTES ===");
        for (Participante part : participantes) {
            if (part == null) {
                System.err.println("ERROR: Participante NULL encontrado en lista_participantes");
                continue;
            }
            System.out.println("\n---------------------------------------");
            System.out.println("Participante: " + part.getNombre() +
                               " (" + part.getEmail() + ")");
            System.out.println("---------------------------------------");

            System.out.println("Pronósticos:");
            for (PronosticoPartido pr : part.getPronosticos()) {

                System.out.print("  Partido " + pr.getNumeroPartido() + ": ");

                if (pr.isDoble())
                    System.out.print("(X) ");

                System.out.println(
                    pr.getEquipoLocal() + " " + pr.getGolesLocal() +
                    " - " + pr.getGolesVisitante() + " " + pr.getEquipoVisitante()
                );
            }

            System.out.println("Total de pronósticos dobles (X): " + part.getDobles());
        }

        // ===== FINAL =====
        System.out.println("\n>>> Parseo COMPLETO: campeonato, fixture, series y participantes cargados correctamente.");
        System.out.println(">>> PROCESAMIENTO FINALIZADO.\n");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // campeonato ::= CAMPEONATO nombre_compuesto NUMERO 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int anioleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int anioright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer anio = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    //Creamos el objeto de campeonato
                    String n = nombre;
                    int a = anio;

                    campeonatoActual = new Campeonato(n, a);

                    System.out.println(">>> Campeonato cargado: " + n + " (" + a + ")");
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("campeonato",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // nombre_compuesto ::= NOMBRE 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // nombre_compuesto ::= nombre_compuesto NOMBRE 
            {
              String RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String prev = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = prev + " " + n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre_compuesto",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // fixture ::= FIXTURE 
            {
              Object RESULT =null;
		
        // (acciones fixture)
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fixture",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // series ::= serie 
            {
              List<Serie> RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("series",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // series ::= series serie 
            {
              List<Serie> RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("series",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // serie ::= SERIE nombre_compuesto EQUIPOS CORCHETE_ABRE lista_equipos CORCHETE_CIERRE partidos 
            {
              Serie RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int equipsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int equipsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<String> equips = (List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int partListleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int partListright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Partido> partList = (List<Partido>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                //Creamos el objeto de seriie
                String nom = nombre;
                serieActual = new Serie(nom);

                // Agregamos los equipos cargados previamente
                List<String> equipos = equips;

                // ===== VALIDACIÓN: EXACTAMENTE 4 EQUIPOS =====
                if (equipos.size() != 4) {
                    System.err.println(
                        "ERROR: La serie '" + nom + "' tiene " + equipos.size() +
                        " equipos. Se esperaban exactamente 4."
                    );
                }

                // ==== Luego sí agregamos los equipos ====
                for (String e : equipos) serieActual.addEquipo(e);

                // Agregamos los partidos ya cargados
                List<Partido> partidos = partList;
                for (Partido p : partidos) {

                    // ===== VALIDACIÓN: equipo local pertenece a la serie =====
                    if (!equipos.contains(p.equipoLocal)) {
                        System.err.println(
                            "ERROR: En la serie '" + nom + "', el equipo local '" +
                            p.equipoLocal + "' NO pertenece a los 4 equipos de la serie."
                        );
                    }

                    // ===== VALIDACIÓN: equipo visitante pertenece a la serie =====
                    if (!equipos.contains(p.equipoVisitante)) {
                        System.err.println(
                            "ERROR: En la serie '" + nom + "', el equipo visitante '" +
                            p.equipoVisitante + "' NO pertenece a los 4 equipos de la serie."
                        );
                    }

                    // Agregar a la serie después de validar
                    serieActual.addPartido(p);
                }

                campeonatoActual.agregarSerie(serieActual);
                System.out.println(">>> Serie cargada: " + nom + " con " + equipos.size() + " equipos y estos son: " + equipos + ". Cantidad de partidos de la serie: " + partidos.size() + " partidos.");
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("serie",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // equipo ::= NOMBRE 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // equipo ::= equipo NOMBRE 
            {
              String RESULT =null;
		int prevleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int prevright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String prev = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = prev + " " + n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_equipos ::= equipo 
            {
              List<String> RESULT =null;
		int elemleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elemright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String elem = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     List<String> lista1 = new ArrayList<>();
                     lista1.add(elem);
                     RESULT = lista1;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_equipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_equipos ::= lista_equipos COMA equipo 
            {
              List<String> RESULT =null;
		int lstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<String> lst = (List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int elemleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elemright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String elem = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     List<String> lista2 = lst;
                     lista2.add(elem);
                     RESULT = lista2;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_equipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // partidos ::= partido 
            {
              List<Partido> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Partido p = (Partido)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<Partido> lista1 = new ArrayList<>();
                lista1.add(p);
                RESULT = lista1;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partidos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // partidos ::= partidos partido 
            {
              List<Partido> RESULT =null;
		int lstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Partido> lst = (List<Partido>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Partido p = (Partido)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<Partido> lista2 = lst;
                lista2.add(p);
                RESULT = lista2;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partidos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // partido ::= PARTIDO_NRO NUMERO FECHA GUION ESTADIO equipo NUMERO GUION equipo NUMERO 
            {
              Partido RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int fechaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int fecharight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String fecha = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String est = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int localleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int localright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String local = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int gLleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int gLright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer gL = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int visitanteleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int visitanteright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String visitante = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int gVleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int gVright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer gV = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                int n = num;
                String f = fecha;
                String e = est;

                String equipoLocal = local;
                int golesEquipoLocal = gL;
                String equipoVisitante = visitante;
                int golesEquipoVisitante = gV;

                Partido p = new Partido(n, f, e, equipoLocal, golesEquipoLocal, equipoVisitante, golesEquipoVisitante);

                partidosPorNumero.put(n, p);

                RESULT = p;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partido",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // participantes_nt ::= participante 
            {
              List<Participante> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Participante p = (Participante)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    List<Participante> lista1 = new ArrayList<>();
                    lista1.add(p);
                    participantes = lista1;   // variable global
                    RESULT = lista1;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participantes_nt",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // participantes_nt ::= participantes_nt participante 
            {
              List<Participante> RESULT =null;
		int lstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Participante> lst = (List<Participante>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Participante p = (Participante)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    lst.add(p);
                    participantes = lst;       // variable global
                    RESULT = lst;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participantes_nt",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // participante ::= SEPARADOR PARTICIPANTE nombre_compuesto GUION EMAIL PRONOSTICOS_PARTIDOS pronosticos 
            {
              Participante RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int emailleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int emailright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String email = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<PronosticoPartido> lista = (List<PronosticoPartido>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    String nom = nombre;
                    String mail = email;

                    Participante participante = new Participante(nom, mail);

                    List<PronosticoPartido> l = lista;

                    // ===== VALIDACIÓN DE PRONÓSTICOS =====
                    for (PronosticoPartido pr : l) {

                        int numPr = pr.getNumeroPartido();

                        // 1) VALIDAR EXISTENCIA DE PARTIDO
                        Partido real = partidosPorNumero.get(numPr);
                        if (real == null) {
                            System.err.println(
                                "ERROR: El participante '" + nom + "' pronosticó el partido Nro " +
                                numPr + " que NO existe en el fixture."
                            );
                            continue; // no seguimos validando este pronóstico
                        }

                        // 2) VALIDAR QUE LOS EQUIPOS COINCIDEN
                        if (!real.getEquipoLocal().equals(pr.getEquipoLocal())) {
                            System.err.println(
                                "ERROR: En el pronóstico del partido " + numPr +
                                " el equipo local '" + pr.getEquipoLocal() +
                                "' no coincide con el fixture ('" + real.getEquipoLocal() + "')."
                            );
                        }

                        if (!real.getEquipoVisitante().equals(pr.getEquipoVisitante())) {
                            System.err.println(
                                "ERROR: En el pronóstico del partido " + numPr +
                                " el equipo visitante '" + pr.getEquipoVisitante() +
                                "' no coincide con el fixture ('" + real.getEquipoVisitante() + "')."
                            );
                        }

                        // Agregar el pronóstico ya validado
                        participante.addPronostico(pr);
                    }

                    // Guardar participante en la lista global
                    RESULT = participante;

                    // UN participante no puede tener mas de 4 marcas
                    if (participante.getDobles() > 4) {
                        System.err.println("ERROR: El participante '" + nom +
                                           "' tiene " + participante.getDobles() +
                                           " pronósticos dobles. Máximo permitido: 4.");
                    }

                    System.out.println(">>> Participante cargado: " + nom + " (" + mail +
                        ") con " + l.size() + " pronósticos.");
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participante",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // pronosticos ::= pronostico 
            {
              List<PronosticoPartido> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		PronosticoPartido p = (PronosticoPartido)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    List<PronosticoPartido> lista1 = new ArrayList<>();
                    lista1.add(p);
                    RESULT = lista1;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronosticos",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // pronosticos ::= pronosticos pronostico 
            {
              List<PronosticoPartido> RESULT =null;
		int lstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<PronosticoPartido> lst = (List<PronosticoPartido>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		PronosticoPartido p = (PronosticoPartido)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    List<PronosticoPartido> lista2 = lst;
                    lista2.add(p);
                    RESULT = lista2;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronosticos",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // pronostico ::= NUMERO DOSPUNTOS equipo NUMERO GUION equipo NUMERO 
            {
              PronosticoPartido RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int localleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int localright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String local = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int gLleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int gLright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer gL = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int visitanteleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int visitanteright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String visitante = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int gVleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int gVright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer gV = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    int n = num;

                    String equipoLocal = local;
                    int golesEquipoLocal = gL;
                    String equipoVisitante = visitante;
                    int golesEquipoVisitante = gV;

                    RESULT = new PronosticoPartido(n, equipoLocal, golesEquipoLocal, equipoVisitante, golesEquipoVisitante, false);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronostico",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // pronostico ::= NUMERO DOSPUNTOS DOBLE equipo NUMERO GUION equipo NUMERO 
            {
              PronosticoPartido RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int localleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int localright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String local = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int gLleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int gLright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer gL = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int visitanteleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int visitanteright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String visitante = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int gVleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int gVright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer gV = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    int n = num;

                    String equipoLocal = local;
                    int golesEquipoLocal = gL;
                    String equipoVisitante = visitante;
                    int golesEquipoVisitante = gV;

                    RESULT = new PronosticoPartido(n, equipoLocal, golesEquipoLocal, equipoVisitante, golesEquipoVisitante, true);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronostico",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
