
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUIPOS = 5;
  public static final int CORCHETE_CIERRE = 10;
  public static final int GUION = 13;
  public static final int DOSPUNTOS = 12;
  public static final int CORCHETE_ABRE = 9;
  public static final int EMAIL = 18;
  public static final int SERIE = 4;
  public static final int PARTIDO_NRO = 6;
  public static final int PRONOSTICOS_PARTIDOS = 8;
  public static final int CAMPEONATO = 2;
  public static final int SEPARADOR = 14;
  public static final int COMA = 11;
  public static final int NOMBRE = 20;
  public static final int FIXTURE = 3;
  public static final int EOF = 0;
  public static final int DOBLE = 15;
  public static final int FECHA = 17;
  public static final int error = 1;
  public static final int NUMERO = 16;
  public static final int ESTADIO = 19;
  public static final int PARTICIPANTE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CAMPEONATO",
  "FIXTURE",
  "SERIE",
  "EQUIPOS",
  "PARTIDO_NRO",
  "PARTICIPANTE",
  "PRONOSTICOS_PARTIDOS",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRE",
  "COMA",
  "DOSPUNTOS",
  "GUION",
  "SEPARADOR",
  "DOBLE",
  "NUMERO",
  "FECHA",
  "EMAIL",
  "ESTADIO",
  "NOMBRE"
  };
}

